all:
	gcc fin01.c -o fin01

	gcc fin02.c -o fin02
	
	gcc fin03.c -o fin03
	
	gcc fin04.c -o fin04
	
	gcc fin05.c -o fin05

clean:
	rm -rf fin01
	
	rm -rf fin02
	
	rm -rf fin03
	
	rm -rf fin04
	
	rm -rf fin05