all:
	gcc hw0201.c -c -o hw0201.o
	gcc myIrrational.c -c -o myIrrational.o
	gcc hw0201.o myIrrational.o -o hw0201 -lm

	gcc hw0202.c -c -o hw0202.o
	gcc myMultiplication.c -c -o myMultiplication.o
	gcc hw0202.o myMultiplication.o -o hw0202 -lm

	gcc hw0203.c -c -o hw0203.o
	gcc myNDFSM.c -c -o myNDFSM.o
	gcc hw0203.o myNDFSM.o -o hw0203

	gcc hw0204.c -c -o hw0204.o
	gcc myDCAC.c -c -o myDCAC.o
	gcc hw0204.o myDCAC.o -o hw0204 -lm

	gcc hw0205.c -c -o hw0205.o
	gcc myCatan.c -c -o myCatan.o
	gcc hw0205.o myCatan.o -o hw0205

clean:
	rm -f hw0201.o
	rm -f myIrrational.o
	rm -f hw0201

	rm -f hw0202.o
	rm -f myMultiplication.o
	rm -f hw0202

	rm -f hw0203.o
	rm -f myNDFSM.o
	rm -f hw0203

	rm -f hw0204.o
	rm -f myDCAC.o
	rm -f hw0204

	rm -f hw0205.o
	rm -f myCatan.o
	rm -f hw0205

