all:
	gcc hw0301.c -o hw0301 || true
	gcc hw0302.c -Wall -Wextra -o hw0302 || true
	gcc hw0303.c -lm -o hw0303 || true
	gcc hw0305.c -Wall -Wextra -lm -o hw0305 || true

clean:
	rm hw0301 || true
	rm hw0302 || true
	rm hw0303 || true
	rm hw0305 || true