all:
	gcc mid0101.c -o mid0101 -lm || true
	gcc mid0102.c -o mid0102 -lm || true
	gcc mid02.c -o mid02 -lm || true
	gcc mid03.c -o mid03 -lm || true

clean:
	rm mid0101 || true
	rm mid0102 || true
	rm mid02 || true
	rm mid03 || true