all:
	gcc hw0201.c -o hw0201 -lm || true
	gcc hw0202.c -o hw0202 || true
	gcc hw0203.c -o hw0203 -lm || true
	gcc hw0204.c -o hw0204 -lm || true
	gcc hw0205.c -o hw0205 -lm || true

clean:
	rm hw0201
	rm hw0202
	rm hw0203
	rm hw0204
	rm hw0205